[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#155752"
idle_fg = "#E1DEBF"
info_bg = "#259990"

[icons]
name = "awesome"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "





[[block]]
block = "weather"
#format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
format = "{weather} {temp}°"
service = { name = "openweathermap", api_key = "3be5d53611e0ca37d35aa15fe6446846", city_id = "1502026", units = "metric" }

[[block]]
block = "pacman"
interval = 10
format = "{count} updates available"
format_singular = "{count} update available"
format_up_to_date = "ok"

#[[block]]
#block = "docker"
#interval = 2
#format = "{running}/{total}"

#[[block]]
#block = "pomodoro"
#length = 25
#break_length = 5
#message = "Take a break!"
#message = "Отдохни!"
#break_message = "Back to work!"
#break_message = "За работу!"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{Mug}GB/{MTg}GB"
format_swap = "{SUg}GB/{STg}GB"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "temperature"
collapsed = false
interval = 10
#format = "{min}° min, {max}° max, {average}° avg"
format = "{average}°"
#chip = "*-isa-*"
chip = "coretemp-isa-0000" #sensors -u

[[block]]
block = "cpu"
interval = 1
info     = 60
warning  = 70
critical = 80
#format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "load"
interval = 1
#format = "{1m} {5m} {15m}"
format = "{1m}"


#[[block]]
#block = "net"
#device = "enp3s0"
#ip = true
#speed_up = false
#raph_down = true
#interval = 5
#use_bits = false

[[block]]
block = "sound"
#driver = "pulseaudio"
on_click = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
show_volume_when_muted = true

#[[block]]
#block = "music"
#buttons = ["play", "next"]

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
#format = "%a %d-%m-%Y %R"
